using ArticleService.Application;
using ArticleService.Domain.Entity;
using Microsoft.EntityFrameworkCore;

namespace ArticleService.Infrastructure.Persistence;

public sealed class SqlArticleService(ArticleDbContext dbContext) : IArticleService
{
    public IReadOnlyCollection<Article> GetAll()
    {
        return dbContext.Articles
            .AsNoTracking()
            .OrderBy(article => article.ArticleId)
            .ToArray();
    }

    public Article? GetById(int articleId)
    {
        return dbContext.Articles
            .AsNoTracking()
            .SingleOrDefault(article => article.ArticleId == articleId);
    }

    public Article Create(Article article)
    {
        // Ensure that the ArticleId is not set, as it will be generated by the database.
        article.ArticleId = 0;

        dbContext.Articles.Add(article);
        dbContext.SaveChanges();

        return article;
    }

    public bool Update(int articleId, Article article)
    {
        var existingArticle = dbContext.Articles.Find(articleId);

        if (existingArticle is null)
        {
            return false;
        }

        existingArticle.Omschrijving = article.Omschrijving;
        existingArticle.Eenheid = article.Eenheid;

        dbContext.SaveChanges();

        return true;
    }

    public bool Delete(int articleId)
    {
        var existingArticle = dbContext.Articles.Find(articleId);

        if (existingArticle is null)
        {
            return false;
        }

        dbContext.Articles.Remove(existingArticle);
        dbContext.SaveChanges();

        return true;
    }
}
