using ArticleService.Application.Interfaces;
using ArticleService.Domain.Entity;
using Microsoft.EntityFrameworkCore;

namespace ArticleService.Infrastructure.Persistence;

public sealed class SqlArticleService(ArticleDbContext dbContext) : IArticleRepository
{
    public async Task<IReadOnlyCollection<Article>> GetAll()
    {
        return await dbContext.Articles
            .AsNoTracking()
            .OrderBy(article => article.ArticleId)
            .ToArrayAsync();
    }

    public Task<Article?> GetById(int articleId)
    {
        return dbContext.Articles
            .AsNoTracking()
            .SingleOrDefaultAsync(article => article.ArticleId == articleId);
    }

    public async Task<Article> Create(Article article)
    {
        // Ensure that the ArticleId is not set, as it will be generated by the database.
        article.ArticleId = 0;

        await dbContext.Articles.AddAsync(article);
        await dbContext.SaveChangesAsync();

        return article;
    }

    public async Task<bool> Update(int articleId, Article article)
    {
        var existingArticle = await dbContext.Articles.FindAsync(articleId);

        if (existingArticle is null)
        {
            return false;
        }

        existingArticle.Description = article.Description;
        existingArticle.Unit = article.Unit;

        await dbContext.SaveChangesAsync();

        return true;
    }
}
